CREATE SCHEMA `Bluefoot_database` ;
CREATE TABLE `Bluefoot_database`.`Users` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NULL,
  `Password` VARCHAR(20) NULL,
  `USERkey` MEDIUMBLOB NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) VISIBLE,
  UNIQUE INDEX `USERkey_UNIQUE` (`USERkey` ASC) VISIBLE);